
####################################### BASIC MISC

spring:
  application:
    name: spring-cloud-eureka-feign-client

server:
  port: 8080

####################################### Eureka Configuration Properties

eureka:
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http:http://localhost:8761/eureka}
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
